name: Feature-CI

on:
  push:
    branches:
      - feature/**
  pull_request:
    branches:
      - feature/**

env:
  CI: true

jobs:

  ##############################
  # 🏷️ FETCH & FAST-FAIL STAGE #
  ##############################

  feature-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: 🚫 Skip if WIP (case-insensitive)
        run: |
          if echo "${{ github.event.head_commit.message }}" | grep -i 'wip'; then
            echo "WIP commit detected, skipping..."
            exit 78
          fi

      - name: ✅ Checkout Code
        uses: actions/checkout@v4

      ##############################
      # ♻️ Cache Dependencies
      ##############################
      - name: ♻️ Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.cache/pip
          key: ${{ runner.os }}-deps-${{ hashFiles('**/package-lock.json', '**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: 🧩 Static Code Analysis (Linting)
        run: |
          echo "Run linter"
          # npm run lint or flake8 .

      - name: 🛡️ Dependency & Vulnerability Scanning
        run: |
          echo "Run dependency scan"
          # npm audit or pip-audit

      - name: 🧪 Run Unit Tests (fail-fast)
        run: |
          echo "Run unit tests"
          # npm test -- --bail

      - name: 🧪 Run Mocked Integration Tests (fail-fast)
        run: |
          echo "Run mocked integration tests"
          # pytest tests/integration --mock

      - name: 📋 Upload Summary
        if: always()
        run: |
          echo "### 🧪 Feature CI Results" >> $GITHUB_STEP_SUMMARY
          echo "- Static Analysis: ✅" >> $GITHUB_STEP_SUMMARY
          echo "- Dependencies: ✅" >> $GITHUB_STEP_SUMMARY
          echo "- Unit Tests: ✅" >> $GITHUB_STEP_SUMMARY
          echo "- Integration Tests: ✅" >> $GITHUB_STEP_SUMMARY
